name: Deploy to AWS

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/OIDC_role
          aws-region: ap-southeast-2
          audience: sts.amazonaws.com

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      # - name: Run tests
      #   run: |
      #     yarn test

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Plan
        env:
          TF_LOG: DEBUG
        run: terraform plan -out=tfplan
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform/

      - name: Get S3 bucket name from Terraform
        id: terraform_output
        run: echo "BUCKET_NAME=$(terraform output -raw bsf_bucket_name)" >> $GITHUB_ENV

      - name: Build and Deploy Frontend
        run: |
          yarn install
          yarn build
          aws s3 sync build/ s3://${{ env.BUCKET_NAME }} --delete
        # env:
        #   REACT_APP_BACKEND_API_URL: ${{ secrets.BACKEND_API_URL }}

      # Save Frontend URL
      - name: Get Backend API URL
        run: terraform output frontend_url
        working-directory: terraform/
